---
- name: "NTP Config Playbook"
  hosts: usa
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "Loop through NTP servers and configure"
      vars:
        myservers:
          - "10.1.10.13"
          - "10.159.12.29"
      cisco.ios.ios_ntp_global:
        config:
          peers:
            - peer: "{{ item }}"
              version: 2
      loop: "{{ myservers }}"
