---
wireless:
  profile:
    - policy: "Guest_Web_Auth"
    - policy: "KIIGuest_Web_Auth"
    - policy: "Person_Web_Auth"

wlan:
  - profile: "Business"
    id: "3"
    ssid: "Business"

  - profile: "Koch-Guest"
    id: "4"
    ssid: "Koch-Guest"

  - profile: "Koch-Personal"
    id: "5"
    ssid: "Koch-Personal"

std_vlans:
  vlan:
    - number: 901
      name: "Wireless_Management"
      svi: "10.59.125.250 255.255.255.0"

    - number: 100
      name: "Client_Vlan"
      svi: "10.59.100.3 255.255.255.0"

    - number: 334
      name: "334-HIOT"
      svi: "172.18.16.3 255.255.255.0"

vlans:
  vlan:
    - number: 893
      name: "893-MLXIOT"
      svi: "172.18.6.4 255.255.255.0"

    - number: 889
      name: "889-MII-Deployment"
      svi: "172.26.16.4 255.255.248.0"

    - number: 890
      name: "890-MII-Deployment"
      svi: "172.26.0.4 255.255.240.0"

    - number: 891
      name: "891-Standard-Vendor-Access"
      svi: "172.18.3.4 255.255.255.0"

    - number: 877
      name: "877-Plating"
      svi: "172.26.42.4 255.255.254.0"

    - number: 878
      name: "878-Molding"
      svi: "172.26.44.4 255.255.254.0"

    - number: 879
      name: "879-Stamping"
      svi: "172.26.46.4 255.255.254.0"

    - number: 880
      name: "880-Assembly"
      svi: "172.26.48.4 255.255.254.0"

    - number: 881
      name: "881-Vision-Systems"
      svi: "172.26.38.4 255.255.254.0"

    - number: 882
      name: "882-Vision-Systems"
      svi: "172.26.40.4 255.255.254.0"

Radius:
  servers:
    - server: "MLXETTRADPSN1"
      ip: "10.244.13.9"
      key: "153R@d!u$KBSLP"

    - server: "MLXLILRADPSN01"
      ip: "10.1.38.101"
      key: "10.1.38.101"

Tacacs:
  servers:
    - server: "MLXETTRADPSN1"
      ip: "10.224.13.9"
      key: "32v51K4BSQskAXWKg1pA"

    - server: "MLXLILRADPSN01"
      ip: "10.1.38.101"
      key: "32v51K4BSQskAXWKg1pA"
